config/routes.rb
Myproductiveday::Application.routes.draw do
  root "people#index"

  resource :settings, only: [:show, :update]
  resources :people, except: [:new]
  resources :reports, only: [:index, :show]
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :reports
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :person
  belongs_to :summary_report, :foreign_key => 'parent_report_id', :class_name => "Report"
  has_many   :person_reports, :foreign_key => 'parent_report_id', :class_name => "Report"

  scope :summary, -> { where(parent_report_id: nil) }
end

app/models/settings.rb
class Settings < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate

  protected

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['login'] && password == ENV['password']
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, except: [:create, :new, :index]

  def index
    @people = Person.all

    @person = Person.new
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to people_path, notice: "Person successfully added"
    else
      redirect_to people_path, alert: "Can't create a new person"
    end
  end

  def new
    @person = Person.new
  end

  def show
  end

  def destroy
    if @person.destroy
      redirect_to people_path, notice: "Person successfully deleted"
    else
      redirect_to people_path, alert: "Sorry, can't delete a person"
    end
  end

  def update
    if @person.update_attributes(person_params)
      redirect_to people_path, notice: "Person successfully updated"
    else
      redirect_to people_path, alert: "Can't update a person"
    end
  end

  private

  def person_params
    params.require(:person).permit(:email)
  end

  def set_person
    @person = Person.find(:id)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = Report.summary
  end

  def person
    @reports = Person.find(params[:person_id]).reports
  end

  def show
    @report = Report.find(params[:id])
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_settings

  def show
  end

  def update
    @settings.update_attributes(settings_params)

    redirect_to settings_path
  end

  private

    def set_settings
      @settings = Settings.first
    end

    def settings_params
      params.require(:settings).permit(:title, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/base/index.html.erb
<h1>Base#index</h1>
<p>Find me in app/views/base/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myproductiveday</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul>
  <li><%= link_to "Settings", settings_path %></li>
  <li><%= link_to "Reports",  reports_path  %></li>
  <li><%= link_to "People",   people_path   %></li>
</ul>

<%= yield %>

</body>
</html>

app/views/people/index.html.erb
<h1>People</h1>

<% @people.each do |person| %>
  <%= person.email %>
<% end %>

<%= form_for @person do |f| %>
  <%= f.text_field :email %>
  <%= f.submit %>
<% end %>

app/views/people/show.html.erb
<h1>People#show</h1>
<p>Find me in app/views/people/show.html.erb</p>

app/views/reports/index.html.erb
<h1>Reports</h1>

<% @reports.each do |report| %>
  <%= @report.created_at %>
<% end %>

app/views/reports/show.html.erb
<h1>Reports#show</h1>
<p>Find me in app/views/reports/show.html.erb</p>

app/views/settings/show.html.erb
<h1>Settings</h1>

<%= form_for @settings, :url => { :action => :update }, :html => { :method => 'put' } do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, value: @settings.title %>
  <%= f.label :text %>
  <%= f.text_area :text, value: @settings.text %>
  <%= f.submit%>
<% end %>

app/views/settings/update.html.erb
<h1>Settings#update</h1>
<p>Find me in app/views/settings/update.html.erb</p>